# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AircraftType'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Station'),
        ),
    ]
