# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_auto_20180527_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Aircraft'),
        ),
    ]
