# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180527_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftmajorassembly',
            name='customer',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
            preserve_default=False,
        ),
    ]
