# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='workorder_number',
            field=models.IntegerField(default=0),
        ),
    ]
