# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_station_workorder_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='workorder_number',
            new_name='last_workorder_number',
        ),
    ]
